name=CocoLinx nRF9151_Shield AT Parser Library
version=2.0.0
author=CocoLinx
maintainer=CocoLinx <info@cocolinx.com>
sentence=AT command parser library for nRF9151_Shield
paragraph=This library provides APIs for modem information, LTE connection, UDP, TCP, MQTT, secure UDP, secure TCP, secure MQTT, GNSS, RS485, and date/time functions.
category=Communication
url=https://github.com/cocolinx/nRF9151_Shield_Library
architectures=*